.TH gonhang "Sep 12, 2020"
.SH NAME
GonhaNG - The Next Generation Light-Weight System Monitor for Linux
.SH SYNOPSIS
\fBgonhang\fR

.SH DESCRIPTION
.B GonhaNG\fR is a System Monitor for several important hardware variables.


.SH ERRORS
Errors must be reported in github : (https://github.com/fredcox/gonhang).

.SH AUTHOR
Fred Lins  (https://fredcox.github.io)
